name: CI Checks
on:
  pull_request:    # Run workflow when a new PR is created, synchronized or re-opened
  push:
    branches:
      - master  # Run workflow when commits are pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry export -f requirements.txt --with dev --output requirements.txt
          pip install -r requirements.txt

      - name: Run tests
        # Run tox using the version of Python in `PATH`
        run: tox -e py
