name: CI Checks
on:
  pull_request:    # Run workflow when a new PR is created, synchronized or re-opened
  push:
    branches:
      - master  # Run workflow when commits are pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry export -f requirements.txt --with dev --output requirements.txt
          pip install -r requirements.txt

      - name: Run tests
        run: tox
